"""
Template service — fetches project templates from MongoDB.
Falls back to in-memory defaults if DB unavailable.
"""
import logging
from typing import Dict
from motor.motor_asyncio import AsyncIOMotorClient, AsyncIOMotorDatabase

logger = logging.getLogger(__name__)

MONGO_URI = "mongodb://localhost:27017/"
DB_NAME = "testgen_suite"
COLLECTION_NAME = "Templates"
PROJECT_NAME = "REACT"
VERSION = "v1"

_template_client: AsyncIOMotorClient | None = None


def _get_template_db() -> AsyncIOMotorDatabase:
    global _template_client
    if _template_client is None:
        _template_client = AsyncIOMotorClient(MONGO_URI, serverSelectionTimeoutMS=5000)
    return _template_client[DB_NAME]

_BASE_TEMPLATE: Dict[str, str] = {
    "src/App.tsx": """\
import React from 'react';
import { BrowserRouter, Routes, Route } from 'react-router-dom';

// AUTO_IMPORTS_START
// AUTO_IMPORTS_END

export default function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route
          path="/"
          element={
            <div className="flex items-center justify-center min-h-screen bg-gray-950 text-white">
              <div className="text-center space-y-3">
                <h1 className="text-4xl font-bold tracking-tight">Your App</h1>
                <p className="text-gray-400">Generated by AI</p>
              </div>
            </div>
          }
        />
        {/* AUTO_ROUTES_START */}
        {/* AUTO_ROUTES_END */}
      </Routes>
    </BrowserRouter>
  );
}
""",
    "src/main.tsx": """\
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';
import App from './App';

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>
);
""",
    "src/index.css": """\
@tailwind base;
@tailwind components;
@tailwind utilities;
""",
    "package.json": """\
{
  "name": "ai-generated-app",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-router-dom": "^6.30.1",
    "recharts": "^2.15.0",
    "lucide-react": "^0.462.0",
    "clsx": "^2.1.1"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.3.1",
    "tailwindcss": "^3.4.17",
    "autoprefixer": "^10.4.21",
    "postcss": "^8.5.6",
    "vite": "^5.4.19",
    "typescript": "^5.8.3"
  }
}
""",
}


async def get_template(project_name: str = PROJECT_NAME, version: str = VERSION) -> Dict[str, str]:
    """
    Fetch template files from MongoDB.
    
    Args:
        project_name: Project type (e.g., "REACT")
        version: Template version (e.g., "v1")
    
    Returns:
        Dict mapping file paths to their contents.
        Falls back to default template if DB unavailable or template not found.
    """
    try:
        db = _get_template_db()
        collection = db[COLLECTION_NAME]
        
        template_doc = await collection.find_one({
            "project_name": project_name,
            "version": version
        })
        
        if not template_doc:
            logger.warning(f"[Template] No template found for {project_name} {version}, using default")
            return dict(_BASE_TEMPLATE)
        
        files: Dict[str, str] = {}
        
        if "files" in template_doc and isinstance(template_doc["files"], list):
            for file_entry in template_doc["files"]:
                path = file_entry.get("path")
                content = file_entry.get("content")
                if path and content:
                    files[path] = content
        
        if not files:
            logger.warning(f"[Template] Template {project_name} {version} has no files, using default")
            return dict(_BASE_TEMPLATE)
        
        logger.info(f"[Template] Loaded template {project_name} {version} with {len(files)} files")
        return files
        
    except Exception as e:
        logger.error(f"[Template] Failed to fetch template from MongoDB: {e}")
        return dict(_BASE_TEMPLATE)


def get_default_template() -> Dict[str, str]:
    """Return the in-memory default template."""
    return dict(_BASE_TEMPLATE)
