"""AI IDE routes — workspace creation (REST) + streaming generation (WebSocket)."""
from fastapi import APIRouter, HTTPException, WebSocket, WebSocketDisconnect
from pydantic import BaseModel

from app.engines.injector import inject_routes
from app.engines.planner import plan_files
from app.engines.generator import stream_file
from app.services import ai_ide_service
from app.services import vercel_service

router = APIRouter(prefix="/ai-ide", tags=["AI IDE"])


def _fallback_content(path: str, component_name: str | None = None) -> str:
    if component_name and path.endswith(".tsx"):
        safe_name = "".join([c for c in component_name if c.isalnum()]) or "Component"
        return (
            "import React from 'react';\n\n"
            f"export default function {safe_name}() {{\n"
            "  return (\n"
            "    <section className=\"p-6\">\n"
            f"      <h1 className=\"text-2xl font-semibold\">{safe_name}</h1>\n"
            "      <p className=\"text-sm text-muted-foreground mt-2\">Generated by AI IDE</p>\n"
            "    </section>\n"
            "  );\n"
            "}\n"
        )

    return ai_ide_service.default_content_for_path(path)


class CreateFileRequest(BaseModel):
    workspace_id: str
    path: str
    content: str = ""


class UpdateFileRequest(BaseModel):
    workspace_id: str
    path: str
    content: str


class DeletePathRequest(BaseModel):
    workspace_id: str
    path: str


class RenamePathRequest(BaseModel):
    workspace_id: str
    from_path: str
    to_path: str


class MovePathRequest(BaseModel):
    workspace_id: str
    from_path: str
    to_path: str


class GitInitPushRequest(BaseModel):
    workspace_id: str
    github_token: str
    repo_name: str
    private: bool = True
    description: str = ""
    branch: str = "main"


class GitCommitPushRequest(BaseModel):
    workspace_id: str
    message: str = "chore: update AI IDE workspace"
    branch: str | None = None


class DeployWorkspaceRequest(BaseModel):
    workspace_id: str
    branch: str | None = None
    target: str = "production"


# ── REST ─────────────────────────────────────────────────────────────────────

@router.post("/workspace/create")
async def create_workspace():
    workspace_id = await ai_ide_service.create_workspace()
    files = ai_ide_service.list_file_paths(workspace_id)
    return {"workspace_id": workspace_id, "file_paths": files}


@router.get("/workspace/{workspace_id}/files")
async def get_files(workspace_id: str):
    try:
        return ai_ide_service.get_workspace_files(workspace_id)
    except KeyError:
        raise HTTPException(status_code=404, detail="Workspace not found")


@router.post("/file/create")
async def create_file(payload: CreateFileRequest):
    try:
        content = payload.content if payload.content.strip() else _fallback_content(payload.path)
        ai_ide_service.create_file(payload.workspace_id, payload.path, content)
        return {"ok": True, "path": payload.path, "content": content}
    except KeyError:
        raise HTTPException(status_code=404, detail="Workspace not found")


@router.post("/file/update")
async def update_file(payload: UpdateFileRequest):
    try:
        ai_ide_service.save_file(payload.workspace_id, payload.path, payload.content)
        return {"ok": True, "path": payload.path}
    except KeyError:
        raise HTTPException(status_code=404, detail="Workspace not found")


@router.post("/file/delete")
async def delete_file(payload: DeletePathRequest):
    try:
        deleted = ai_ide_service.delete_path(payload.workspace_id, payload.path)
        return {"ok": True, "deleted": deleted}
    except KeyError:
        raise HTTPException(status_code=404, detail="Workspace not found")


@router.post("/file/rename")
async def rename_path(payload: RenamePathRequest):
    try:
        updated = ai_ide_service.rename_or_move_path(
            payload.workspace_id,
            payload.from_path,
            payload.to_path,
        )
        return {"ok": True, "updated": updated}
    except KeyError:
        raise HTTPException(status_code=404, detail="Workspace not found")


@router.post("/file/move")
async def move_path(payload: MovePathRequest):
    try:
        updated = ai_ide_service.rename_or_move_path(
            payload.workspace_id,
            payload.from_path,
            payload.to_path,
        )
        return {"ok": True, "updated": updated}
    except KeyError:
        raise HTTPException(status_code=404, detail="Workspace not found")


@router.post("/git/init-and-push")
async def ai_ide_git_init_and_push(payload: GitInitPushRequest):
    try:
        return await ai_ide_service.init_git_and_create_repo(
            workspace_id=payload.workspace_id,
            github_token=payload.github_token,
            repo_name=payload.repo_name,
            private=payload.private,
            description=payload.description,
            branch=payload.branch,
        )
    except KeyError:
        raise HTTPException(status_code=404, detail="Workspace not found")
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc))


@router.post("/git/commit-and-push")
async def ai_ide_git_commit_and_push(payload: GitCommitPushRequest):
    try:
        return await ai_ide_service.commit_and_push_workspace(
            workspace_id=payload.workspace_id,
            message=payload.message,
            branch=payload.branch,
        )
    except KeyError:
        raise HTTPException(status_code=404, detail="Workspace not found")
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc))


@router.post("/deploy")
async def ai_ide_deploy(payload: DeployWorkspaceRequest):
    try:
        meta = ai_ide_service.get_workspace_meta(payload.workspace_id)
        repo_url = meta.get("repo_url")
        if not repo_url:
            raise HTTPException(status_code=400, detail="Initialize and push repository before deploying")

        branch = (payload.branch or meta.get("default_branch") or "main").strip() or "main"
        return await vercel_service.trigger_deployment(
            branch=branch,
            repo_url=repo_url,
            commit_sha=None,
            target=payload.target,
        )
    except KeyError:
        raise HTTPException(status_code=404, detail="Workspace not found")
    except vercel_service.VercelServiceError as exc:
        raise HTTPException(status_code=exc.status_code, detail=exc.message)


# ── WebSocket ─────────────────────────────────────────────────────────────────

@router.websocket("/ws/generate/{workspace_id}")
async def generate(ws: WebSocket, workspace_id: str):
    """
    Protocol:
      client → server : plain text idea  (first message)
      server → client : typed JSON events (see WSEvent schema below)

    Events:
      {"type": "STATUS",         "message": str}
      {"type": "FILE_CREATE",    "path": str}
      {"type": "STREAM_TOKEN",   "path": str, "token": str}
      {"type": "FILE_DONE",      "path": str}
      {"type": "FILE_UPDATE",    "path": str, "content": str}
      {"type": "GENERATION_DONE"}
      {"type": "ERROR",          "message": str}
    """
    await ws.accept()

    try:
        # Validate workspace exists
        try:
            ai_ide_service.get_workspace_files(workspace_id)
        except KeyError:
            await ws.send_json({"type": "ERROR", "message": "Workspace not found"})
            await ws.close(code=4004)
            return

        # Step 1: receive idea
        idea = await ws.receive_text()
        if not idea.strip():
            await ws.send_json({"type": "ERROR", "message": "Empty idea"})
            return

        # Step 2: plan
        await ws.send_json({"type": "STATUS", "message": "Planning your app…"})
        try:
            plan = await plan_files(idea)
        except Exception as exc:
            await ws.send_json({"type": "ERROR", "message": f"Planner error: {exc}"})
            return

        files_list = plan.get("files", [])
        routes_list = plan.get("routes", [])

        if not files_list:
            await ws.send_json({"type": "ERROR", "message": "Planner returned no files"})
            return

        await ws.send_json({
            "type": "STATUS",
            "message": f"Plan ready — generating {len(files_list)} file(s)…",
        })

        # Step 3: generate each file with streaming
        for file_spec in files_list:
            path = file_spec.get("path", "src/pages/Page.tsx")

            await ws.send_json({"type": "FILE_CREATE", "path": path})

            content = ""
            async for token in stream_file(file_spec):
                content += token
                await ws.send_json({"type": "STREAM_TOKEN", "path": path, "token": token})

            if not content.strip():
                content = _fallback_content(path, file_spec.get("component_name"))
                await ws.send_json({
                    "type": "FILE_UPDATE",
                    "path": path,
                    "content": content,
                })

            ai_ide_service.save_file(workspace_id, path, content)
            await ws.send_json({"type": "FILE_DONE", "path": path})

        # Step 4: inject routes into App.tsx
        if routes_list:
            try:
                app_tsx = ai_ide_service.read_file(workspace_id, "src/App.tsx")
                updated_app = inject_routes(app_tsx, routes_list)
                ai_ide_service.save_file(workspace_id, "src/App.tsx", updated_app)
                await ws.send_json({
                    "type": "FILE_UPDATE",
                    "path": "src/App.tsx",
                    "content": updated_app,
                })
            except Exception as exc:
                # Non-fatal: generation still completed, just routes not injected
                await ws.send_json({
                    "type": "STATUS",
                    "message": f"Warning: route injection failed — {exc}",
                })

        await ws.send_json({"type": "GENERATION_DONE"})

    except WebSocketDisconnect:
        pass
    except Exception as exc:
        try:
            await ws.send_json({"type": "ERROR", "message": str(exc)})
        except Exception:
            pass
